name: Art Integration
description: Add art to game
title: "[ART]: "
labels: ["art"]
assignees: []
body:   
  - type: textarea
    id: art-description
    attributes:
      label: Description of what will be added or updated
      description: Give us a brief description of what kind of artwork will be added into the game. Also specify if it is 2D or 3D.
    validations:
      required: true
      
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: |
        Provide any additional information such as screenshots, reference cards, etc.