name: Game Mechanics Implementation
description: Add or update game mechanic(s)
title: "[MECHANIC]: "
labels: ["game-design"]
assignees: []
body:   
  - type: textarea
    id: mechanic-description
    attributes:
      label: Description of what will be added or updated
      description: Give us a brief description of what kind of mechanic will be added into the game.
    validations:
      required: true
      
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: |
        Provide any additional information such as screenshots, reference cards, etc.